CREATE TABLE IF NOT EXISTS USERS(
ID VARCHAR2(8) PRIMARY KEY,
PASSWORD VARCHAR2(8),
NAME VARCHAR2(20),
ROLE VARCHAR2(5)
);


INSERT INTO USERS VALUES('KIM', '1234', 'KIMGILDONG', 'ADMIN');


INSERT INTO USERS VALUES
('PARK', '1234', 'PARKWONSOON', 'ADMIN'),
('AN', '1234', 'ANCHOELSOO', 'ADMIN')
;


SELECT * FROM USERS;